apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-service
  labels:
    app: hello-nginx
spec:
  type: LoadBalancer  # EKS will create an ELB
  selector:
    app: hello-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
